# @package _global_
env:
  # PSO env settings
  problem_sig: "cvrp"
  n_particles: 2

  # Problem general specific settings
  n_dims: 2

  training_cfg:
    batch_size: 1
    steps_per_epoch: 128
  
  validation_cfg:
    batch_size: 1
    random_include: False
    random_size: 100
    
  test_cfg:
    enable: True
    batch_size: 1
    random_include: False
    random_size: 1280

aco_agent:
  n_cities: [20, 50, 100, 200, 500, 1000]
  n_ants: [5, 10, 20, 20, 50, 100]
  aco_iterations_infer: 10
  n_gnn_feats: 4
  use_nls: False
  w_nls: 0.95

log:
  save_dir: "./logs"
  name: "aco_cvrp"
  version: "default"