# @package _global_
env:
  test_cfg:
    batch_size: 8
    k_sparse: 20
    n_cities: 100
  training_cfg:
    batch_size: 4
    k_sparse: 20
    n_cities: 100
  validation_cfg:
    batch_size: 8
    k_sparse: 20
    n_cities: 100
