# @package _global_
env:
  test_cfg:
    batch_size: 2
    k_sparse: '[5, 10, 20, 20, 50]'
    mode: '"choice"'
    n_cities: '[20, 50, 100, 200, 500]'
  training_cfg:
    batch_size: 16
    k_sparse: '[5, 10, 20]'
    mode: '"range"'
    n_cities: '[20, 50, 100]'
  validation_cfg:
    batch_size: 8
    k_sparse: '[5, 10, 20]'
    mode: '"choice"'
    n_cities: '[20, 50, 100]'
