# @package _global_
env:
  n_particles: 128
  test_cfg:
    batch_size: 1
    k_sparse: 20
    n_cities: 200
  training_cfg:
    batch_size: 1
    k_sparse: 20
    n_cities: 200
  validation_cfg:
    batch_size: 2
    k_sparse: 20
    n_cities: 200
