# @package _global_
env:
  test_cfg:
    batch_size: 2
    k_sparse: 10
    n_cities: 50
  training_cfg:
    batch_size: 8
    k_sparse: 10
    n_cities: 50
  validation_cfg:
    batch_size: 16
    k_sparse: 10
    n_cities: 50
